[package]
name = "lab1b-rust"
version = "0.1.0"
authors = ["Zhouyu Qian <qzy@qzy.io>"]

[dependencies]
termios = "0.3"
nix = { git = "https://github.com/nix-rust/nix.git", rev = "c2fb79e2fd6ecc15589f532459db06a506696efa" }
